/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author aemal4075
 */
public class NewJFrame extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */
    public NewJFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblInstruction = new javax.swing.JLabel();
        lblFirstInput = new javax.swing.JLabel();
        btnCheckAnswer = new javax.swing.JButton();
        lblOneChoiceA = new javax.swing.JLabel();
        lblOneChoiceB = new javax.swing.JLabel();
        lblOneChoiceC = new javax.swing.JLabel();
        lblOneChoiceD = new javax.swing.JLabel();
        lblSeconndInput = new javax.swing.JLabel();
        lblTwoChoiceA = new javax.swing.JLabel();
        lblTwoChoiceB = new javax.swing.JLabel();
        lblTwoChoiceC = new javax.swing.JLabel();
        lblTwoChoiceD = new javax.swing.JLabel();
        lblOutputTwo = new javax.swing.JTextField();
        lblOutputOne = new javax.swing.JTextField();
        lblCorrectAnswer = new javax.swing.JLabel();
        lblIncorrectAnswer = new javax.swing.JLabel();
        lblScorePercent = new javax.swing.JLabel();
        lblOutputCA = new javax.swing.JLabel();
        lblOutputIA = new javax.swing.JLabel();
        lblOutputSP = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblInstruction.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblInstruction.setText("Analyze and choose the right Answer.");

        lblFirstInput.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblFirstInput.setText("1) It involves creating instructions for a computer to follow.");

        btnCheckAnswer.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnCheckAnswer.setText("Check Your Answer!");
        btnCheckAnswer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCheckAnswerActionPerformed(evt);
            }
        });

        lblOneChoiceA.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblOneChoiceA.setText("a) Computer Technology ");

        lblOneChoiceB.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblOneChoiceB.setText("b) Computer Programming");

        lblOneChoiceC.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblOneChoiceC.setText("c) Computer Science");

        lblOneChoiceD.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblOneChoiceD.setText("d) Computer Engineering");

        lblSeconndInput.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblSeconndInput.setText("2) Which of the following is not an example of peripheral?");

        lblTwoChoiceA.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblTwoChoiceA.setText("a) printer");

        lblTwoChoiceB.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblTwoChoiceB.setText("b) scanner");

        lblTwoChoiceC.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblTwoChoiceC.setText("c) hard drive");

        lblTwoChoiceD.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblTwoChoiceD.setText("d) mouse ");

        lblOutputOne.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lblOutputOneActionPerformed(evt);
            }
        });

        lblCorrectAnswer.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblCorrectAnswer.setText("Correct Answers:");

        lblIncorrectAnswer.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblIncorrectAnswer.setText("Incorrect Answer:");

        lblScorePercent.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblScorePercent.setText("Score Percentage:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblFirstInput, javax.swing.GroupLayout.PREFERRED_SIZE, 369, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(40, 40, 40)
                        .addComponent(lblOutputOne, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lblOneChoiceA, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblOneChoiceB, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(60, 60, 60)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblOneChoiceC, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblOneChoiceD, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblSeconndInput, javax.swing.GroupLayout.PREFERRED_SIZE, 378, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(28, 28, 28)
                        .addComponent(lblOutputTwo))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblTwoChoiceA, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblTwoChoiceB))
                        .addGap(55, 55, 55)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblTwoChoiceD)
                            .addComponent(lblTwoChoiceC)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(147, 147, 147)
                        .addComponent(btnCheckAnswer, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(84, 84, 84)
                        .addComponent(lblInstruction, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lblCorrectAnswer, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblIncorrectAnswer, javax.swing.GroupLayout.DEFAULT_SIZE, 137, Short.MAX_VALUE)
                            .addComponent(lblScorePercent, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(82, 82, 82)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lblOutputCA, javax.swing.GroupLayout.DEFAULT_SIZE, 94, Short.MAX_VALUE)
                            .addComponent(lblOutputIA, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblOutputSP, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(44, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblInstruction, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblFirstInput, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblOutputOne, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblOneChoiceA, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblOneChoiceC, javax.swing.GroupLayout.DEFAULT_SIZE, 24, Short.MAX_VALUE)
                        .addGap(4, 4, 4)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblOneChoiceB, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblOneChoiceD, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblSeconndInput, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblOutputTwo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblTwoChoiceC)
                    .addComponent(lblTwoChoiceA, javax.swing.GroupLayout.DEFAULT_SIZE, 19, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblTwoChoiceB)
                    .addComponent(lblTwoChoiceD))
                .addGap(28, 28, 28)
                .addComponent(btnCheckAnswer, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblCorrectAnswer, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblOutputCA, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(6, 6, 6)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblIncorrectAnswer, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblOutputIA, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(4, 4, 4)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblScorePercent, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblOutputSP, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(7, 7, 7)))
                .addContainerGap(36, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCheckAnswerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCheckAnswerActionPerformed
        String useranswer1, useranswer2; 
        double numcorrect, numincorrect, score_percentage, total_question;
        int first,second; 
        int num1, num2, num3, num4;
        
        num1 = 0 ;
        num2 = 0 ;
        num3 = 0 ; 
        num4 = 2 ;
        
        numcorrect = 0; 
        numincorrect = 0; 
        total_question = 2;
                
        useranswer1 = (lblOutputOne.getText());
        if(useranswer1.equals("b")){
            numcorrect = numcorrect + 1;
        }
        else
        {
            numincorrect= numincorrect + 1; 
        }
            
        useranswer2 = (lblOutputTwo.getText());
        if(useranswer2.equals("c")){
            numcorrect = numcorrect + 1;
        }
        else
        {
            numincorrect = numincorrect + 1; 
        }
        
        
        
        
        score_percentage = (numcorrect / total_question)* 100; 
        
        score_percentage = score_percentage * 1000; 
        score_percentage = Math.round(score_percentage);
        score_percentage = score_percentage / 1000; 
        
        lblOutputSP.setText(String.valueOf(score_percentage));
        lblOutputCA.setText(String.valueOf(numcorrect));
        lblOutputIA.setText(String.valueOf(numincorrect));
        
        
        
        




// TODO add your handling code here:
    }//GEN-LAST:event_btnCheckAnswerActionPerformed

    private void lblOutputOneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lblOutputOneActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lblOutputOneActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCheckAnswer;
    private javax.swing.JLabel lblCorrectAnswer;
    private javax.swing.JLabel lblFirstInput;
    private javax.swing.JLabel lblIncorrectAnswer;
    private javax.swing.JLabel lblInstruction;
    private javax.swing.JLabel lblOneChoiceA;
    private javax.swing.JLabel lblOneChoiceB;
    private javax.swing.JLabel lblOneChoiceC;
    private javax.swing.JLabel lblOneChoiceD;
    private javax.swing.JLabel lblOutputCA;
    private javax.swing.JLabel lblOutputIA;
    private javax.swing.JTextField lblOutputOne;
    private javax.swing.JLabel lblOutputSP;
    private javax.swing.JTextField lblOutputTwo;
    private javax.swing.JLabel lblScorePercent;
    private javax.swing.JLabel lblSeconndInput;
    private javax.swing.JLabel lblTwoChoiceA;
    private javax.swing.JLabel lblTwoChoiceB;
    private javax.swing.JLabel lblTwoChoiceC;
    private javax.swing.JLabel lblTwoChoiceD;
    // End of variables declaration//GEN-END:variables
}
